from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel

METRICS_SCHEMA_VERSION = "2026.03.25-analysis-r2"


class MetricFamily(StrEnum):
    DIAGNOSTICS = "diagnostics"
    PRESENCE_ATTENTION = "presence_attention"
    PERCEPTION = "perception"
    INTERACTION_STRUCTURE = "interaction_structure"


class MetricContract(BaseModel):
    metric_name: str
    metric_family: MetricFamily
    grain: str
    numerator: str
    denominator: str
    unresolved_handling: str
    null_handling: str
    intended_use: str
    anti_use: str
    metric_definition_version: str


def metric_contract_registry() -> dict[str, MetricContract]:
    return {
        "mention_volume": MetricContract(
            metric_name="mention_volume",
            metric_family=MetricFamily.DIAGNOSTICS,
            grain="whole result set",
            numerator="count of normalized mentions",
            denominator="not applicable",
            unresolved_handling="includes all mentions regardless of entity resolution",
            null_handling="not applicable",
            intended_use="baseline volume and denominator for rate metrics",
            anti_use="not a proxy for entity attention or author reach",
            metric_definition_version="2.0.0",
        ),
        "resolved_entity_mention_rate": MetricContract(
            metric_name="resolved_entity_mention_rate",
            metric_family=MetricFamily.DIAGNOSTICS,
            grain="whole result set",
            numerator="mentions with at least one canonical entity fact",
            denominator="all mentions",
            unresolved_handling="unresolved mentions remain in denominator and not numerator",
            null_handling="mentions with no entity facts count as unresolved",
            intended_use="diagnosing entity resolution coverage",
            anti_use="not a business share metric",
            metric_definition_version="2.0.0",
        ),
        "reviewable_low_confidence_rate": MetricContract(
            metric_name="reviewable_low_confidence_rate",
            metric_family=MetricFamily.DIAGNOSTICS,
            grain="whole result set",
            numerator="mentions with low-confidence classification or unresolved entity review items",
            denominator="all mentions",
            unresolved_handling="reviewable unresolved items contribute to numerator",
            null_handling="missing review rows count as zero",
            intended_use="operational monitoring of model/rule uncertainty",
            anti_use="not a perception or quality metric",
            metric_definition_version="2.0.0",
        ),
        "aspect_fact_total": MetricContract(
            metric_name="aspect_fact_total",
            metric_family=MetricFamily.DIAGNOSTICS,
            grain="whole result set",
            numerator="aspect opinion facts with non-null aspect labels",
            denominator="not applicable",
            unresolved_handling="target unresolved state does not suppress aspect fact counting",
            null_handling="facts with null aspect labels excluded",
            intended_use="diagnosing total aspect fact emission volume before grouped perception slicing",
            anti_use="not a per-aspect attention metric",
            metric_definition_version="1.0.0",
        ),
        "sov_by_mentions": MetricContract(
            metric_name="sov_by_mentions",
            metric_family=MetricFamily.PRESENCE_ATTENTION,
            grain="canonical entity",
            numerator="distinct mentions that reference the entity at least once",
            denominator="all mentions in the slice",
            unresolved_handling="unresolved mentions stay in denominator and are excluded from numerator",
            null_handling="null canonical entities excluded from entity rows",
            intended_use="entity presence share at mention grain",
            anti_use="not interchangeable with hit-count share or resolved-only share",
            metric_definition_version="2.0.0",
        ),
        "sov_by_entity_hits": MetricContract(
            metric_name="sov_by_entity_hits",
            metric_family=MetricFamily.PRESENCE_ATTENTION,
            grain="canonical entity",
            numerator="entity-hit rows for the entity",
            denominator="all entity-hit rows including repeated entities per mention",
            unresolved_handling="unresolved rows excluded from both numerator and denominator",
            null_handling="null canonical entities excluded",
            intended_use="multi-entity attention share at hit grain",
            anti_use="not suitable when stakeholders expect mention-level exclusivity",
            metric_definition_version="2.0.0",
        ),
        "sov_resolved_mentions_only": MetricContract(
            metric_name="sov_resolved_mentions_only",
            metric_family=MetricFamily.PRESENCE_ATTENTION,
            grain="canonical entity",
            numerator="distinct resolved mentions that reference the entity",
            denominator="mentions with at least one resolved entity",
            unresolved_handling="unresolved mentions excluded from denominator",
            null_handling="null canonical entities excluded",
            intended_use="clean resolved-only share-of-voice comparisons",
            anti_use="not comparable to whole-slice mention share without noting denominator change",
            metric_definition_version="2.0.0",
        ),
        "mention_sentiment_distribution": MetricContract(
            metric_name="mention_sentiment_distribution",
            metric_family=MetricFamily.PERCEPTION,
            grain="sentiment label",
            numerator="mention-level sentiment facts per label",
            denominator="all mention-level sentiment facts",
            unresolved_handling="not applicable because mention sentiment is always emitted",
            null_handling="rows with null sentiment excluded",
            intended_use="top-level conversational mood",
            anti_use="not target-specific perception",
            metric_definition_version="2.0.0",
        ),
        "target_sentiment_distribution_global": MetricContract(
            metric_name="target_sentiment_distribution_global",
            metric_family=MetricFamily.PERCEPTION,
            grain="sentiment label",
            numerator="target sentiment facts per sentiment label",
            denominator="all target sentiment facts",
            unresolved_handling="unresolved target facts stay in denominator and are grouped by sentiment only",
            null_handling="rows with null sentiment excluded",
            intended_use="overall target-aware sentiment mix across the slice",
            anti_use="not a per-target distribution",
            metric_definition_version="1.0.0",
        ),
        "target_sentiment_distribution": MetricContract(
            metric_name="target_sentiment_distribution",
            metric_family=MetricFamily.PERCEPTION,
            grain="canonical business target and sentiment label",
            numerator="target sentiment facts per canonical entity or approved concept target and label",
            denominator="all target sentiment facts for the canonical business target",
            unresolved_handling="unresolved or surface-only targets are excluded from the business-facing distribution",
            null_handling="null business target keys or null sentiment labels excluded",
            intended_use="business-facing canonical target perception analysis",
            anti_use="not a forensic surface-variant breakdown",
            metric_definition_version="4.0.0",
        ),
        "target_sentiment_distribution_forensic": MetricContract(
            metric_name="target_sentiment_distribution_forensic",
            metric_family=MetricFamily.PERCEPTION,
            grain="raw target key, surface text, and sentiment label",
            numerator="target sentiment facts per raw target surface and label",
            denominator="all target sentiment facts for the raw target key",
            unresolved_handling="surface-only and unresolved targets remain visible in this forensic lane",
            null_handling="null target keys or null sentiment labels excluded",
            intended_use="forensic/debug inspection of target surface fragmentation",
            anti_use="not the canonical business target view",
            metric_definition_version="1.0.0",
        ),
        "aspect_occurrence_count": MetricContract(
            metric_name="aspect_occurrence_count",
            metric_family=MetricFamily.PERCEPTION,
            grain="aspect label",
            numerator="aspect opinion facts for the aspect",
            denominator="not applicable",
            unresolved_handling="target unresolved state does not suppress aspect occurrence",
            null_handling="null aspects excluded",
            intended_use="measuring aspect attention frequency",
            anti_use="not sentiment or issue severity",
            metric_definition_version="3.0.0",
        ),
        "aspect_target_pair_count": MetricContract(
            metric_name="aspect_target_pair_count",
            metric_family=MetricFamily.PERCEPTION,
            grain="aspect label and canonical business target",
            numerator="aspect opinion facts grouped by aspect and canonical entity or approved concept target",
            denominator="not applicable",
            unresolved_handling="unresolved or surface-only targets excluded from the business-facing pair count",
            null_handling="facts with no business target key excluded",
            intended_use="business-facing who-is-being-discussed on which aspect",
            anti_use="not a forensic surface-target breakdown",
            metric_definition_version="4.0.0",
        ),
        "aspect_target_pair_count_forensic": MetricContract(
            metric_name="aspect_target_pair_count_forensic",
            metric_family=MetricFamily.PERCEPTION,
            grain="aspect label and raw target key",
            numerator="aspect opinion facts grouped by aspect and raw target key",
            denominator="not applicable",
            unresolved_handling="surface-only targets remain visible in this forensic lane",
            null_handling="facts with no raw target key excluded",
            intended_use="forensic/debug target surface inspection for aspects",
            anti_use="not the canonical business aspect view",
            metric_definition_version="1.0.0",
        ),
        "aspect_sentiment_distribution": MetricContract(
            metric_name="aspect_sentiment_distribution",
            metric_family=MetricFamily.PERCEPTION,
            grain="aspect label and sentiment label",
            numerator="aspect opinion facts per aspect and sentiment",
            denominator="all aspect opinion facts for the aspect",
            unresolved_handling="target resolution does not affect inclusion",
            null_handling="facts with null aspect or sentiment excluded",
            intended_use="local aspect polarity mix",
            anti_use="not a target-specific satisfaction score",
            metric_definition_version="3.0.0",
        ),
        "aspect_sentiment_resolved_only": MetricContract(
            metric_name="aspect_sentiment_resolved_only",
            metric_family=MetricFamily.PERCEPTION,
            grain="aspect label and sentiment label",
            numerator="aspect opinion facts with canonical targets per aspect and sentiment",
            denominator="aspect opinion facts with canonical targets for the aspect",
            unresolved_handling="unresolved targets excluded from denominator",
            null_handling="facts with null aspect or sentiment excluded",
            intended_use="entity-resolved aspect perception tracking",
            anti_use="not comparable to all-aspect distribution without noting resolved-only denominator",
            metric_definition_version="3.0.0",
        ),
        "issue_signal_rate_global": MetricContract(
            metric_name="issue_signal_rate_global",
            metric_family=MetricFamily.PERCEPTION,
            grain="whole result set",
            numerator="issue signal facts with non-null issue class",
            denominator="all mentions",
            unresolved_handling="target resolution does not affect inclusion",
            null_handling="facts with null issue classes excluded",
            intended_use="overall issue pressure across the slice",
            anti_use="not a per-issue-class prevalence metric",
            metric_definition_version="1.0.0",
        ),
        "issue_signal_rate": MetricContract(
            metric_name="issue_signal_rate",
            metric_family=MetricFamily.PERCEPTION,
            grain="issue class",
            numerator="issue signal facts for the issue class",
            denominator="all mentions",
            unresolved_handling="target resolution does not affect issue inclusion",
            null_handling="null issue classes excluded",
            intended_use="issue prevalence monitoring",
            anti_use="not severity or confirmation rate by itself",
            metric_definition_version="3.0.0",
        ),
        "issue_confirmed_rate": MetricContract(
            metric_name="issue_confirmed_rate",
            metric_family=MetricFamily.PERCEPTION,
            grain="issue class",
            numerator="issue signal facts with direct complaint or direct observation evidence mode",
            denominator="all issue signal facts for the issue class",
            unresolved_handling="target unresolved state does not affect denominator",
            null_handling="facts with null evidence mode excluded",
            intended_use="separating grounded issue evidence from uncertain evidence",
            anti_use="not a defect rate or verified incident rate",
            metric_definition_version="3.0.0",
        ),
        "issue_direct_complaint_rate": MetricContract(
            metric_name="issue_direct_complaint_rate",
            metric_family=MetricFamily.PERCEPTION,
            grain="issue class",
            numerator="issue signal facts with direct complaint evidence mode",
            denominator="all issue signal facts for the issue class",
            unresolved_handling="target unresolved state does not affect denominator",
            null_handling="facts with null evidence mode excluded",
            intended_use="monitoring direct complaint pressure",
            anti_use="not total issue prevalence",
            metric_definition_version="3.0.0",
        ),
        "issue_uncertain_rate": MetricContract(
            metric_name="issue_uncertain_rate",
            metric_family=MetricFamily.PERCEPTION,
            grain="issue class",
            numerator="issue signal facts with question_or_uncertainty or hearsay_or_rumor evidence mode",
            denominator="all issue signal facts for the issue class",
            unresolved_handling="target unresolved state does not affect denominator",
            null_handling="facts with null evidence mode excluded",
            intended_use="surfacing uncertain issue discourse separately from direct complaints",
            anti_use="not a confirmed issue metric",
            metric_definition_version="3.0.0",
        ),
        "severe_issue_rate": MetricContract(
            metric_name="severe_issue_rate",
            metric_family=MetricFamily.PERCEPTION,
            grain="issue class",
            numerator="issue signal facts with severity high or critical_like_proxy",
            denominator="all issue signal facts for the issue class",
            unresolved_handling="target unresolved state does not affect denominator",
            null_handling="facts with null severity excluded",
            intended_use="tracking higher-severity issue pressure",
            anti_use="not equivalent to negative sentiment or legal severity",
            metric_definition_version="3.0.0",
        ),
        "author_concentration": MetricContract(
            metric_name="author_concentration",
            metric_family=MetricFamily.INTERACTION_STRUCTURE,
            grain="author",
            numerator="mentions authored by the author",
            denominator="all mentions",
            unresolved_handling="not applicable",
            null_handling="null author ids excluded",
            intended_use="authorship concentration analysis",
            anti_use="not creator reach or influence quality",
            metric_definition_version="2.0.0",
        ),
        "thread_initiator_concentration": MetricContract(
            metric_name="thread_initiator_concentration",
            metric_family=MetricFamily.INTERACTION_STRUCTURE,
            grain="thread initiator author",
            numerator="threads initiated by the author",
            denominator="all root threads",
            unresolved_handling="not applicable",
            null_handling="threads without identifiable root author excluded",
            intended_use="who starts conversations",
            anti_use="not total mention concentration",
            metric_definition_version="2.0.0",
        ),
        "channel_concentration": MetricContract(
            metric_name="channel_concentration",
            metric_family=MetricFamily.INTERACTION_STRUCTURE,
            grain="platform/channel",
            numerator="mentions on the channel",
            denominator="all mentions",
            unresolved_handling="not applicable",
            null_handling="null platforms excluded",
            intended_use="channel mix analysis",
            anti_use="not author concentration",
            metric_definition_version="2.0.0",
        ),
        "reply_to_comment_ratio_proxy": MetricContract(
            metric_name="reply_to_comment_ratio_proxy",
            metric_family=MetricFamily.INTERACTION_STRUCTURE,
            grain="thread",
            numerator="reply count plus smoothing constant",
            denominator="comment count plus smoothing constant",
            unresolved_handling="not applicable",
            null_handling="missing counts treated as zero before smoothing",
            intended_use="interaction-shape proxy for recursive discussion depth",
            anti_use="not a true controversy metric",
            metric_definition_version="2.0.0",
        ),
        "interaction_recursion_proxy": MetricContract(
            metric_name="interaction_recursion_proxy",
            metric_family=MetricFamily.INTERACTION_STRUCTURE,
            grain="thread",
            numerator="max observed depth plus descendant participation",
            denominator="not applicable",
            unresolved_handling="not applicable",
            null_handling="missing depth treated as zero",
            intended_use="proxy for recursive conversational structure",
            anti_use="not a validated engagement-quality metric",
            metric_definition_version="2.0.0",
        ),
    }


def family_definition_versions() -> dict[str, str]:
    return {
        MetricFamily.DIAGNOSTICS.value: "3.0.0",
        MetricFamily.PRESENCE_ATTENTION.value: "2.0.0",
        MetricFamily.PERCEPTION.value: "4.0.0",
        MetricFamily.INTERACTION_STRUCTURE.value: "2.0.0",
    }
